/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.team3;

import java.awt.event.WindowEvent;
import java.util.Timer;

/**
 *
 * @author pjrio
 */
public class act_screen extends javax.swing.JFrame {

    javax.swing.JFrame myFrame = this;

    /**
     * Creates new form act_screen
     */
    public act_screen() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

         clock = new Timer();
         jPanel7 = new javax.swing.JPanel();
         jPanel8 = new javax.swing.JPanel();
         teamA = new javax.swing.JPanel();
         TitleA = new javax.swing.JLabel();
         PlayersA = new javax.swing.JPanel();
         jPanel9 = new javax.swing.JPanel();
         jPanel11 = new javax.swing.JPanel();
         red_player1 = new javax.swing.JLabel();
         jPanel12 = new javax.swing.JPanel();
         red_player2 = new javax.swing.JLabel();
         jPanel13 = new javax.swing.JPanel();
         red_player3 = new javax.swing.JLabel();
         jPanel2 = new javax.swing.JPanel();
         jPanel6 = new javax.swing.JPanel();
         red_player4_score = new javax.swing.JLabel();
         jPanel10 = new javax.swing.JPanel();
         red_player2_score = new javax.swing.JLabel();
         jPanel19 = new javax.swing.JPanel();
         red_player1_score = new javax.swing.JLabel();
         jPanel23 = new javax.swing.JPanel();
         red_total_score = new javax.swing.JLabel();
         Sep = new javax.swing.JPanel();
         teamB = new javax.swing.JPanel();
         TitleA1 = new javax.swing.JLabel();
         jPanel3 = new javax.swing.JPanel();
         jPanel14 = new javax.swing.JPanel();
         jPanel15 = new javax.swing.JPanel();
         green_player1 = new javax.swing.JLabel();
         jPanel16 = new javax.swing.JPanel();
         green_player2 = new javax.swing.JLabel();
         jPanel17 = new javax.swing.JPanel();
         green_player4 = new javax.swing.JLabel();
         jPanel18 = new javax.swing.JPanel();
         jPanel20 = new javax.swing.JPanel();
         green_player3_score = new javax.swing.JLabel();
         jPanel21 = new javax.swing.JPanel();
         green_player2_score = new javax.swing.JLabel();
         jPanel22 = new javax.swing.JPanel();
         green_player1_score = new javax.swing.JLabel();
         jPanel5 = new javax.swing.JPanel();
         green_total_score = new javax.swing.JLabel();
         timerText1 = new javax.swing.JLabel();
         timer1 = new javax.swing.JLabel();
         jPanel1 = new javax.swing.JPanel();
         teamB1 = new javax.swing.JPanel();
         jScrollPane3 = new javax.swing.JScrollPane();
         TeamB_update = new javax.swing.JTextArea();
         Sep1 = new javax.swing.JPanel();
         timerText = new javax.swing.JLabel();
         timer = new javax.swing.JLabel();
         teamA1 = new javax.swing.JPanel();
         jScrollPane1 = new javax.swing.JScrollPane();
         TeamA_update = new javax.swing.JTextArea();
         jPanel4 = new javax.swing.JPanel();
         jButtonEndGame = new javax.swing.JButton();
         jLabel1 = new javax.swing.JLabel();
         jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setBackground(new java.awt.Color(0, 51, 255));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(80, 363));

        teamA.setBackground(new java.awt.Color(0, 0, 0));
        teamA.setPreferredSize(new java.awt.Dimension(300, 100));

        TitleA.setBackground(new java.awt.Color(0, 0, 0));
        TitleA.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        TitleA.setForeground(new java.awt.Color(255, 0, 0));
        TitleA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red.png"))); // NOI18N

        PlayersA.setBackground(new java.awt.Color(0, 0, 0));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setMinimumSize(new java.awt.Dimension(257, 250));
        jPanel9.setPreferredSize(new java.awt.Dimension(257, 250));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(159, 32));

        red_player1.setBackground(new java.awt.Color(255, 255, 255));
        red_player1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_player1.setForeground(new java.awt.Color(255, 0, 51));
        red_player1.setText("  Player 1");
        red_player1.setPreferredSize(new java.awt.Dimension(112, 35));
        red_player1.setVisible(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addComponent(red_player1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addGap(68, 68, 68)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(217, 32));

        red_player2.setBackground(new java.awt.Color(0, 0, 0));
        red_player2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_player2.setForeground(new java.awt.Color(255, 0, 51));
        red_player2.setText("  Player 2");
        red_player2.setVisible(false);


        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(red_player2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(red_player2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setPreferredSize(new java.awt.Dimension(253, 35));

        red_player3.setBackground(new java.awt.Color(255, 255, 255));
        red_player3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_player3.setForeground(new java.awt.Color(255, 0, 51));
        red_player3.setText("  Player 3");
        red_player3.setVisible(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 111));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        red_player4_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_player4_score.setForeground(new java.awt.Color(255, 0, 51));
        red_player4_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        red_player4_score.setText("0");
        red_player4_score.setPreferredSize(new java.awt.Dimension(50, 29));
        red_player4_score.setVisible(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player4_score, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player4_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        red_player2_score.setBackground(new java.awt.Color(0, 0, 0));
        red_player2_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_player2_score.setForeground(new java.awt.Color(255, 0, 51));
        red_player2_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        red_player2_score.setText("0");
        red_player2_score.setPreferredSize(new java.awt.Dimension(50, 29));
        red_player2_score.setVisible(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addComponent(red_player2_score, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player2_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 40));

        red_player1_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_player1_score.setForeground(new java.awt.Color(255, 0, 51));
        red_player1_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        red_player1_score.setText("0");
        red_player1_score.setPreferredSize(new java.awt.Dimension(50, 40));
        red_player1_score.setVisible(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_player1_score, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addComponent(red_player1_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout PlayersALayout = new javax.swing.GroupLayout(PlayersA);
        PlayersA.setLayout(PlayersALayout);
        PlayersALayout.setHorizontalGroup(
            PlayersALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        PlayersALayout.setVerticalGroup(
            PlayersALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayersALayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 237, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));
        jPanel23.setPreferredSize(new java.awt.Dimension(121, 55));

        red_total_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        red_total_score.setForeground(new java.awt.Color(255, 0, 51));
        red_total_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        red_total_score.setText("0");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_total_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(red_total_score, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teamALayout = new javax.swing.GroupLayout(teamA);
        teamA.setLayout(teamALayout);
        teamALayout.setHorizontalGroup(
            teamALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleA, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
            .addGroup(teamALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayersA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        teamALayout.setVerticalGroup(
            teamALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamALayout.createSequentialGroup()
                .addComponent(TitleA, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayersA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Sep.setBackground(new java.awt.Color(0, 0, 0));
        Sep.setPreferredSize(new java.awt.Dimension(80, 0));

        javax.swing.GroupLayout SepLayout = new javax.swing.GroupLayout(Sep);
        Sep.setLayout(SepLayout);
        SepLayout.setHorizontalGroup(
            SepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        SepLayout.setVerticalGroup(
            SepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        teamB.setBackground(new java.awt.Color(0, 0, 0));
        teamB.setPreferredSize(new java.awt.Dimension(300, 100));

        TitleA1.setBackground(new java.awt.Color(0, 204, 0));
        TitleA1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        TitleA1.setForeground(new java.awt.Color(0, 204, 0));
        TitleA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green.png"))); // NOI18N
        TitleA1.setMaximumSize(new java.awt.Dimension(301, 108));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setMinimumSize(new java.awt.Dimension(257, 250));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setPreferredSize(new java.awt.Dimension(159, 32));

        green_player1.setBackground(new java.awt.Color(255, 255, 255));
        green_player1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_player1.setForeground(new java.awt.Color(51, 255, 0));
        green_player1.setText("Player 1");
        green_player1.setPreferredSize(new java.awt.Dimension(112, 35));
        green_player1.setVisible(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addComponent(green_player1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setPreferredSize(new java.awt.Dimension(217, 32));

        green_player2.setBackground(new java.awt.Color(0, 0, 0));
        green_player2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_player2.setForeground(new java.awt.Color(51, 255, 0));
        green_player2.setText("Player 2");
        green_player2.setVisible(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(green_player2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(green_player2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel17.setPreferredSize(new java.awt.Dimension(253, 35));

        green_player4.setBackground(new java.awt.Color(255, 255, 255));
        green_player4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_player4.setForeground(new java.awt.Color(51, 255, 0));
        green_player4.setText("Player 3");
        green_player4.setVisible(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setPreferredSize(new java.awt.Dimension(50, 111));

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));

        green_player3_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_player3_score.setForeground(new java.awt.Color(51, 255, 0));
        green_player3_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        green_player3_score.setText("0");
        green_player3_score.setPreferredSize(new java.awt.Dimension(50, 29));
        green_player3_score.setVisible(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player3_score, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player3_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));

        green_player2_score.setBackground(new java.awt.Color(0, 0, 0));
        green_player2_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_player2_score.setForeground(new java.awt.Color(51, 255, 0));
        green_player2_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        green_player2_score.setText("0");
        green_player2_score.setPreferredSize(new java.awt.Dimension(50, 29));
        green_player2_score.setVisible(false);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player2_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player2_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 40));

        green_player1_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_player1_score.setForeground(new java.awt.Color(51, 255, 0));
        green_player1_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        green_player1_score.setText("0");
        green_player1_score.setPreferredSize(new java.awt.Dimension(50, 40));
        green_player1_score.setVisible(false);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green_player1_score, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addComponent(green_player1_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(121, 55));

        green_total_score.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        green_total_score.setForeground(new java.awt.Color(51, 255, 0));
        green_total_score.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        green_total_score.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(green_total_score, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(green_total_score, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout teamBLayout = new javax.swing.GroupLayout(teamB);
        teamB.setLayout(teamBLayout);
        teamBLayout.setHorizontalGroup(
            teamBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teamBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamBLayout.createSequentialGroup()
                        .addGroup(teamBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        teamBLayout.setVerticalGroup(
            teamBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamBLayout.createSequentialGroup()
                .addComponent(TitleA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        timerText1.setBackground(new java.awt.Color(0, 0, 0));
        timerText1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        timerText1.setForeground(new java.awt.Color(255, 255, 255));
        timerText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerText1.setText("Are you ready?");

        timer1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        timer1.setForeground(new java.awt.Color(255, 255, 255));
        timer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timer1.setText("00:00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(teamA, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sep, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(timerText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(timer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamB, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teamA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(timerText1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timer1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(Sep, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(teamB, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        teamB1.setBackground(new java.awt.Color(0, 0, 0));
        teamB1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        teamB1.setPreferredSize(new java.awt.Dimension(300, 100));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TeamB_update.setEditable(false);
        TeamB_update.setBackground(new java.awt.Color(0, 0, 0));
        TeamB_update.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        TeamB_update.setForeground(new java.awt.Color(51, 255, 0));
        TeamB_update.setText("");
        TeamB_update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TeamB_update.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(TeamB_update);

        javax.swing.GroupLayout teamB1Layout = new javax.swing.GroupLayout(teamB1);
        teamB1.setLayout(teamB1Layout);
        teamB1Layout.setHorizontalGroup(
            teamB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamB1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        teamB1Layout.setVerticalGroup(
            teamB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamB1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        Sep1.setBackground(new java.awt.Color(0, 0, 0));
        Sep1.setPreferredSize(new java.awt.Dimension(80, 0));

        timerText.setBackground(new java.awt.Color(0, 0, 0));
        timerText.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        timerText.setForeground(new java.awt.Color(255, 255, 255));
        timerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerText.setText("Remaining Time: ");

        timer.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        timer.setForeground(new java.awt.Color(255, 255, 255));
        timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timer.setText("00:00");

        javax.swing.GroupLayout Sep1Layout = new javax.swing.GroupLayout(Sep1);
        Sep1.setLayout(Sep1Layout);
        Sep1Layout.setHorizontalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sep1Layout.createSequentialGroup()
                .addComponent(timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Sep1Layout.setVerticalGroup(
            Sep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sep1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(timerText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        teamA1.setBackground(new java.awt.Color(0, 0, 0));
        teamA1.setPreferredSize(new java.awt.Dimension(300, 100));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TeamA_update.setEditable(false);
        TeamA_update.setBackground(new java.awt.Color(0, 0, 0));
        TeamA_update.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        TeamA_update.setForeground(new java.awt.Color(255, 0, 51));
        TeamA_update.setText("");
        TeamA_update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TeamA_update.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TeamA_update);

        javax.swing.GroupLayout teamA1Layout = new javax.swing.GroupLayout(teamA1);
        teamA1.setLayout(teamA1Layout);
        teamA1Layout.setHorizontalGroup(
            teamA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        teamA1Layout.setVerticalGroup(
            teamA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

       jButtonEndGame.setBackground(new java.awt.Color(0, 0, 0));
       jButtonEndGame.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
       jButtonEndGame.setForeground(new java.awt.Color(255, 255, 255));
       jButtonEndGame.setText("EXIT");
       jButtonEndGame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
       jButtonEndGame.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButtonEndGameActionPerformed(evt);
           }
       });

       jLabel2.setText(" ");

       javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
       jPanel4.setLayout(jPanel4Layout);
       jPanel4Layout.setHorizontalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGap(18, 18, 18)
               .addComponent(jButtonEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap())
       );
       jPanel4Layout.setVerticalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButtonEndGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addGroup(jPanel4Layout.createSequentialGroup()
                       .addGap(13, 13, 13)
                       .addComponent(jLabel1))
                   .addComponent(jLabel2))
               .addContainerGap())
       );
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(teamA1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sep1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamB1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(Sep1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(teamB1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }// GEN-LAST:event_formWindowStateChanged

    private void jButtonEndGameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEndGameActionPerformed
        // TODO add your handling code here:
        // getParent().dispose();

        // getParent().setVisible(false);
        // window.Close();
        myFrame.dispatchEvent(new WindowEvent(myFrame, WindowEvent.WINDOW_CLOSING));
    }// GEN-LAST:event_jButtonEndGameActionPerformed

    private void dis_Names() {

      //loop over arrays and gets names

      for (int i = 0; i < View.redFirst.size()+1; i++){
        switch (i) {
           case 1:  red_player1.setText(" " + View.redFirst.get(i-1));
                    red_player1.setVisible(true);
                    red_player1_score.setVisible(true);
                    break;
           case 2:  red_player2.setText(" " + View.redFirst.get(i-1));
                    red_player2.setVisible(true);
                    red_player2_score.setVisible(true);
                    break;
           case 3:  red_player3.setText(" " + View.redFirst.get(i-1));
                    red_player3.setVisible(true);
                    red_player4_score.setVisible(true);
                    break;
           // case 4:  red_player4.setText(" " + View.redFirst.get(i-1));
           //          red_player4.setVisible(true);
           //          break;
           // case 5:  mred_player5.setText(" " + View.redFirst.get(i-1));
           //          red_player5.setVisible(true);
           //          break;
        }
      }

      for (int j = 0; j < View.redFirst.size()+1; j++){
        switch (j) {
           case 1:  green_player1.setText("" + View.blueFirst.get(j-1));
                    green_player1.setVisible(true);
                    green_player1_score.setVisible(true);
                    break;
           case 2:  green_player2.setText("" + View.blueFirst.get(j-1));
                    green_player2.setVisible(true);
                    green_player2_score.setVisible(true);
                    break;
           case 3:  green_player4.setText("" + View.blueFirst.get(j-1));
                    green_player4.setVisible(true);
                    green_player3_score.setVisible(true);
                    break;
           // case 4:  monthString = "April";
           //          break;
           // case 5:  monthString = "May";
           //          break;
        }
      }
    }

    //--------------------------------------------------------------------------
    private void update_Scores() {
      for (int i = 0; i < View.redScores.length+1; i++){
        switch (i) {
           case 1:  red_player1_score.setText(" " + View.redScores[i-1]);
                    break;
           case 2:  red_player2_score.setText(" " + View.redScores[i-1]);
                    break;
           case 3:  red_player4_score.setText(" " + View.redScores[i-1]);
                    break;
           // case 4:  red_player4.setText(" " + View.redFirst.get(i-1));
           //          red_player4.setVisible(true);
           //          break;
           // case 5:  mred_player5.setText(" " + View.redFirst.get(i-1));
           //          red_player5.setVisible(true);
           //          break;
        }
      }

      for (int i = 0; i < View.blueScores.length+1; i++){
        switch (i) {
           case 1:  green_player1_score.setText(" " + View.blueScores[i-1]);
                    break;
           case 2:  green_player2_score.setText(" " + View.blueScores[i-1]);
                    break;
           case 3:  green_player3_score.setText(" " + View.blueScores[i-1]);
                    break;
           // case 4:  red_player4.setText(" " + View.redFirst.get(i-1));
           //          red_player4.setVisible(true);
           //          break;
           // case 5:  mred_player5.setText(" " + View.redFirst.get(i-1));
           //          red_player5.setVisible(true);
           //          break;
        }
      }
    }

    //--------------------------------------------------------------------------
    public void max_score() {

      max_red = 0;
      max_green = 0;

      // red max
         for (int i = 1; i < View.redScores.length; i++)
             if (View.redScores[i] > View.redScores[max_red])
                 max_red = i+1;
      // green max
         for (int i = 1; i < View.blueScores.length; i++)
             if (View.blueScores[i] > View.blueScores[max_green])
                 max_green = i+1;
    }

    //--------------------------------------------------------------------------
    public void effect() {
      if (max_red>max_green){
        switch (max_red) {
           case 1:
                    red_player1.setVisible(!visibility);
                    red_player1_score.setVisible(!visibility);
                    break;
           case 2:
                    red_player2.setVisible(!visibility);
                    red_player2_score.setVisible(!visibility);
                    break;
           case 3:
                    red_player3.setVisible(!visibility);
                    red_player4_score.setVisible(!visibility);
                    break;
           // case 4:  red_player4.setText(" " + View.redFirst.get(i-1));
           //          red_player4.setVisible(true);
           //          break;
           // case 5:  mred_player5.setText(" " + View.redFirst.get(i-1));
           //          red_player5.setVisible(true);
           //          break;
        }
      }
    else if(max_green>max_red) {
        switch (max_green) {
           case 1:
                    green_player1.setVisible(!visibility);
                    green_player1_score.setVisible(!visibility);
                    break;
           case 2:
                    green_player2.setVisible(!visibility);
                    green_player2_score.setVisible(!visibility);
                    break;
           case 3:
                    green_player4.setVisible(!visibility);
                    green_player3_score.setVisible(!visibility);
                    break;
           // case 4:  monthString = "April";
           //          break;
           // case 5:  monthString = "May";
           //          break;
        }
      }
      if(View.redScore>View.blueScore){
        green_total_score.setVisible(!visibility);
      }
      else if(View.blueScore>View.redScore)
      {
        red_total_score.setVisible(!visibility);
      }

      visibility= !visibility;


    }

    public void start() {

        visibility =true;
        max_red = 2;
        max_green = 0;
        java.util.TimerTask task = this.new UpdatePlayerEntry();
        clock.schedule(task, 500, 1000);

    }

    class UpdatePlayerEntry extends java.util.TimerTask {

        int progressBar = 30;
        int totalSeconds = 360;
        int seconds = 59;

        public UpdatePlayerEntry() {
            /* Create and display the form */
            new act_screen().setVisible(true);

            //display names from array
            dis_Names();

            timer.setVisible(false);
            timerText.setVisible(false);


        }

        public void update() {
            if (progressBar > 0) {
                progressBar--;
            } else {
                timer1.setVisible(false);
                timerText1.setVisible(false);
            }

            if (totalSeconds > 0 && progressBar == 0) {
                totalSeconds--;
            }

            if (seconds >= 0 && progressBar == 0) {
                seconds--;
            } else {
                seconds = 59;
            }
        }

        @Override
        public void run() {
            // Increase loading bar percentage
            String out = String.valueOf(progressBar);
            out = String.format("%2s", out).replace(' ', '0');
            timer1.setText("00:" + out);

            //show counter and update boards
            if (progressBar == 0) {
                timer.setVisible(true);
                timerText.setVisible(true);
                red_total_score.setText(" " + View.redScore);
                green_total_score.setText(" " + View.blueScore);
                update_Scores();
                effect();
                if (DatagramServer.red_signal==true)
                {
                  TeamA_update.setForeground(new java.awt.Color(255, 0, 51));
                  TeamA_update.append(" action: " + DatagramServer.to_print);
                  TeamA_update.setCaretPosition(TeamA_update.getDocument().getLength());
                  DatagramServer.red_signal=false;
                }

                if (DatagramServer.grn_signal==true)
                    {
                    TeamB_update.setForeground(new java.awt.Color(51, 255, 0));
                    TeamB_update.append(" action: " + DatagramServer.to_print);
                    TeamB_update.setCaretPosition(TeamB_update.getDocument().getLength());
                    DatagramServer.grn_signal=false;
                }

            }

            String out2 = String.valueOf(seconds);
            out2 = String.format("%2s", out2).replace(' ', '0');

            if (totalSeconds > 300) {
                timer.setText("05:" + out2);
            } else if (totalSeconds < 300 && totalSeconds >= 240) {
                timer.setText("04:" + out2);
            } else if (totalSeconds < 240 && totalSeconds >= 180) {
                timer.setText("03:" + out2);
            } else if (totalSeconds < 180 && totalSeconds >= 120) {
                timer.setText("02:" + out2);
            } else if (totalSeconds < 120 && totalSeconds >= 60) {
                timer.setText("01:" + out2);
            } else if (totalSeconds < 60 && totalSeconds > 0) {
                timer.setText("00:" + out2);
            }

            this.update();
        }
    }

    // Variables declaration
    static boolean visibility;
    static int max_red;
    static int max_green;
    private static java.util.Timer clock;
    private javax.swing.JPanel PlayersA;
    private javax.swing.JPanel Sep;
    private javax.swing.JPanel Sep1;
    private static javax.swing.JTextArea TeamA_update;
    private static javax.swing.JTextArea TeamB_update;
    private javax.swing.JLabel TitleA;
    private javax.swing.JLabel TitleA1;
    private static javax.swing.JLabel green_player1;
    private static javax.swing.JLabel green_player1_score;
    private static javax.swing.JLabel green_player2;
    private static javax.swing.JLabel green_player2_score;
    private static javax.swing.JLabel green_player3_score;
    private static javax.swing.JLabel green_player4;
    private static javax.swing.JLabel green_total_score;
    private javax.swing.JButton jButtonEndGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JLabel red_player1;
    private static javax.swing.JLabel red_player1_score;
    private static javax.swing.JLabel red_player2;
    private static javax.swing.JLabel red_player2_score;
    private static javax.swing.JLabel red_player3;
    private static javax.swing.JLabel red_player4_score;
    private static javax.swing.JLabel red_total_score;
    private javax.swing.JPanel teamA;
    private javax.swing.JPanel teamA1;
    private javax.swing.JPanel teamB;
    private javax.swing.JPanel teamB1;
    private static javax.swing.JLabel timer;
    private static javax.swing.JLabel timer1;
    private static javax.swing.JLabel timerText;
    private static javax.swing.JLabel timerText1;
    // End of variables declaration//GEN-END:variables
}
