/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.team3;

import com.team3.splashScreen.splashScreen;

public class App {
    Controller controller;
    View view;

    App(){
        controller = new Controller();
        view = new View(controller);
    }
    public static void main(String[] args) {
        splashScreen splashScr = new splashScreen();
        splashScr.start();
        act_screen act_screen = new act_screen();
        App app = new App();
        DBService db = new DBService();
        db.test();
    }
}


