/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.team3;

import com.team3.splashScreen.splashScreen;

public class App {

    public static void main(String[] args) {
        DBService db = new DBService();
        Controller controller = new Controller(db);
        splashScreen splashScr = new splashScreen();
        splashScr.start();
        View view = new View(controller);
        controller.setView(view);
        db.test();
    }
}


